### ISSUE TITLE
Nice work! From where did you find out the topics of the rest of the 20 projects? 

### ISSUE THREAD

**Issue by code-loading** [sshamim/JavaScriptProjects#1]

**Comment by sshamim** [comment]
> _No description provided._

The list of all projects that we are going to do is available on the same drive where lectures are being uploaded.  Let me know if you did not find it and I will share it.

Ping  me over Whatsapp if need be.

**Comment by code-loading** [comment]
I'm not quite sure which drive you're referring to. Could you please share the link here or wherever it's easier for you? 
Thanks!

**Comment by sshamim** [comment]
Send me your email address and I'll share the document that has all the project listings mentioned
